#+TITLE: Signal Handler
#+AUTHOR: Astar Bahouidi
#+DESCRIPTION: Chapter 21 from “The Linux Programming Interface” by Michael Kerrisk
#+STARTUP: showall

* Table Of Contents                                                   :toc_3:
- [[#introduction][Introduction]]
- [[#211-designing-signal-handlers][21.1 Designing Signal Handlers]]
  - [[#2111-signals-are-not-queued-revisited][21.1.1 Signals Are Not Queued (Revisited)]]
  - [[#2112-reentrant-and-async-signal-safe-functions][21.1.2 Reentrant and Async-Signal-Safe Functions]]
    - [[#reentrant-and-nonreentrant-functions][Reentrant and nonreentrant functions]]
    - [[#standard-async-signal-safe-functions][Standard async-signal-safe functions]]
    - [[#signal-handlers-design-traps][Signal Handlers Design Traps]]
    - [[#use-of-errno-inside-signal-handlers][Use of =errno= inside signal handlers]]
    - [[#use-of-unsafe-functions-in-example-programs-in-this-book][Use of unsafe functions in example programs in this book]]
  - [[#2113-global-variables-and-the-sig_atomic_t-data-type][21.1.3 Global Variables and the sig_atomic_t Data Type]]
- [[#212-other-methods-of-terminating-a-signal-handler][21.2 Other Methods of Terminating a Signal Handler]]
  - [[#2121-performing-a-nonlocal-goto-from-a-signal-handler][21.2.1 Performing a Nonlocal Goto from a Signal Handler]]
    - [[#mynote-calling-async-signal-unsafe-after-nonlocal-goto][Mynote: Calling Async-Signal-Unsafe After Nonlocal Goto]]
    - [[#example-program][Example program]]
    - [[#warning-about-nonlocal-goto][Warning about nonlocal goto]]
  - [[#2122-terminating-a-process-abnormally-abort][21.2.2 Terminating a Process Abnormally: abort()]]
- [[#213-handling-a-signal-on-an-alternate-stack-sigaltstack][21.3 Handling a Signal on an Alternate Stack: sigaltstack()]]
- [[#214-the-sa_siginfo-flag][21.4 The SA_SIGINFO Flag]]
  - [[#the-siginfo_t-structure][The =siginfo_t= structure]]
    - [[#table-21-2-values-returned-in-the-siginfo_tsi_code-field][Table 21-2: Values returned in the =siginfo_t.si_code= field]]
  - [[#the-ucontext-argument][The =ucontext= argument]]
- [[#215-interruption-and-restarting-of-system-calls][21.5 Interruption and Restarting of System Calls]]
  - [[#handle-system-calls-interruption-by-signals][Handle System Calls Interruption by Signals]]
  - [[#effects-of-sa_restart-on-system-calls-and-library-functions][Effects Of =SA_RESTART= On System Calls And Library Functions]]
    - [[#system-calls-automatically-restarted-by-sa_restart][System calls automatically restarted by =SA_RESTART=]]
    - [[#system-calls-never-restarted][System calls never restarted]]
  - [[#modifying-the-sa_restart-flag-for-a-signal][Modifying the =SA_RESTART= flag for a signal]]
  - [[#unhandled-stop-signals-can-generate-eintr-for-some-linux-system-calls][Unhandled stop signals can generate =EINTR= for some Linux system calls]]
- [[#216-summary][21.6 Summary]]
  - [[#further-information][Further information]]
- [[#217-exercises][21.7 Exercises]]
  - [[#exercise-211][Exercise 21.1]]
    - [[#answer][Answer]]

* Introduction

This chapter continues the description of signals begun in the
previous chapter.  It focuses on signal handlers, and extends the
discussion started in [[file:CHAPTER_20.org::#section-20-4][Section 20.4]].  Among the topics we consider are
the following:

- *how to design a signal handler*, which necessitates a discussion of
  *reentrancy* and *async-signal-safe* functions;

- *alternatives to performing a normal return from a signal handler*,
  in particular, the use of a *nonlocal goto* for this purpose;

- *handling of signals on an alternate stack*;

- the use of the =sigaction()= =SA_SIGINFO= flag to allow a signal
  handler *to obtain more detailed information* about the signal that
  caused its invocation; and

- *how a blocking system call may be interrupted by a signal handler*,
  and how the call can be restarted if desired.

* 21.1 Designing Signal Handlers
:PROPERTIES:
:CUSTOM_ID: 211-designing-signal-handlers
:END:

In general, it is preferable to write simple signal handlers. One
important reason for this is to reduce the risk of creating race
conditions. Two common designs for signal handlers are the following:

- *The signal handler sets a global flag and exits*. The main program
  periodically checks this flag and, if it is set, takes appropriate
  action. (If the main program cannot perform such periodic checks
  because it needs to monitor one or more file descriptors to see if
  I/O is possible, then the signal handler can also write a single
  byte to a dedicated pipe whose read end is included among the file
  descriptors monitored by the main program. We show an example of
  this technique in Section 63.5.2.)

- *The signal handler performs some type of cleanup and then either
  terminates the process or uses a nonlocal goto* ([[#section-21-2-1][Section 21.2.1]]) to
  unwind the stack and return control to a predetermined location in
  the main program.

In the following sections, we explore these ideas, as well as other
concepts that are important in the design of signal handlers.

** 21.1.1 Signals Are Not Queued (Revisited)
:PROPERTIES:
:CUSTOM_ID: 2111-signals-are-not-queued-(revisited)
:END:

In [[file:README.org::#section-20-10][Section 20.10]], we noted that *delivery of a signal is blocked
during the execution of its handler* (unless we specify the
=SA_NODEFER= flag to =sigaction()=). If the signal is (again)
generated while the handler is executing, then it is marked as pending
and later delivered when the handler returns. We also already noted
that *signals are not queued*. If the signal is generated more than
once while the handler is executing, then it is still marked as
pending, and it will later be delivered only once.

That signals can “disappear” in this way has implications for how we
design signal handlers. To begin with, *we can’t reliably count the
number of times a signal is generated*. Furthermore, *we may need to
code our signal handlers to deal with the possibility that* *multiple
events of the type corresponding to the signal have occurred*. We’ll
see an example of this when we consider the use of the =SIGCHLD=
signal in Section 26.3.1.

** 21.1.2 Reentrant and Async-Signal-Safe Functions
:PROPERTIES:
:CUSTOM_ID: 2112-reentrant-and-async-signal-safe-functions
:END:

*Not all system calls and library functions can be safely called from
a signal handler*.  To understand why requires an explanation of two
concepts: *reentrant functions* and *async-signal-safe functions*.

*** Reentrant and nonreentrant functions

To explain what a reentrant function is, we need to first distinguish between /singlethreaded/ and /multithreaded/ programs. Classical UNIX programs have a single thread of execution: the CPU processes instructions for a single logical flow of execution through the program. In a /multithreaded/ program, there are *multiple*, *independent*, *concurrent logical flows of execution within the same process*.

In [[file:~/coding/c_prog/tlpi/threads/CHAPTER_29.org][Chapter 29]], we’ll see how to explicitly create programs that
contain multiple threads of execution. However, the concept of
multiple threads of execution is also relevant for programs that
employ signal handlers. *Because a signal handler may asynchronously
interrupt the execution of a program at any point in time*, *the main
program and the signal handler* *in effect form two independent
(although not concurrent) threads of execution* *within the same
process*.

**** Reentrancy Definition

A function is said to be /reentrant/ if it can safely be
simultaneously executed by multiple threads of execution in the same
process. In this context, “safe” means that the function achieves its
expected result, regardless of the state of execution of any other
thread of execution.

  #+begin_quote
  The SUSv3 definition of a /reentrant/ function is one *“whose
  effect, when called by two or more threads,* *is guaranteed to be as
  if the threads each executed the function one after the other* *in
  an undefined order, even if the actual execution is interleaved.”*
  #+end_quote

**** Nonreentrancy Specific Conditions

A function may be /nonreentrant/ if *it updates global or static data
structures*. (*A function that employs only local variables is
guaranteed to be reentrant.*) If two invocations of (i.e., two threads
executing) the function simultaneously attempt to update the same
global variable or data structure, then these updates are likely to
interfere with each other and produce incorrect results. For example,
suppose that one thread of execution is in the middle of updating a
linked list data structure to add a new list item when another thread
also attempts to update the same linked list. Since adding a new item
to the list requires updating multiple pointers, if another thread
interrupts these steps and updates the same pointers, chaos will
result.

Such possibilities are in fact rife within the standard C library:

- *Fucntions that rely on global variable*: We already noted in
  Section 7.1.3 that =malloc()= and =free()= maintain a linked list of
  freed memory blocks available for reallocation from the heap. If a
  call to =malloc()= in the main program is interrupted by a signal
  handler that also calls =malloc()=, then this linked list can be
  corrupted. For this reason, the =malloc()= family of functions, and
  other library functions that use them, are /nonreentrant/.

- *Functions that return results through statically allocated memory*:
  Other library functions are /nonreentrant/ because they return
  information using statically allocated memory. Examples of such
  functions (described elsewhere in this book) include =crypt()=,
  =getpwnam()=, =gethostbyname()=, and =getservbyname()=.  If a signal
  handler also uses one of these functions, then it will overwrite
  information returned by any earlier call to the same function from
  within the main program (or vice versa).

- *Functions that maintain static data structures for their internal
  bookkeeping*: Functions can also be /nonreentrant/ if they use
  static data structures for their internal bookkeeping. The most
  obvious examples of such functions are the members of the /stdio/
  library (=printf()=, =scanf()=, and so on), which update internal
  data structures for buffered I/O. Thus, when using =printf()= from
  within a signal handler, we may sometimes see strange output — or
  even a program crash or data corruption — if the handler interrupts
  the main program in the middle of executing a call to =printf()= or
  another /stdio/ function.

- Even if we are not using /nonreentrant/ library functions,
  reentrancy issues can still be relevant. If a signal handler updates
  programmer-defined global data structures that are also updated
  within the main program, then we can say that *the signal handler is
  nonreentrant with respect to the main program.*

If a function is /nonreentrant/, then its manual page will normally
provide an explicit or implicit indication of this fact. In
particular, *watch out for statements that the function uses* or
*returns information in statically allocated variables*.

**** Example Program

[[file:nonreentrant.c][Listing 21.1]] (/nonreentrant.c/) demonstrates the nonreentrant nature of the
=crypt()= function (Section 8.5). As command-line arguments, this
program accepts two strings. The program performs the following steps:

1. Call =crypt()= to encrypt the string in the first command-line
   argument, and copy this string to a separate buffer using
   =strdup()=.

2. Establish a handler for =SIGINT= (generated by typing
   Control-C). The handler calls =crypt()= to encrypt the string
   supplied in the second command-line argument.

3. Enter an infinite for loop that uses =crypt()= to encrypt the
   string in the first command-line argument and check that the
   returned string is the same as that saved in step 1.

In the absence of a signal, the strings will always match in
step 3. However, if a =SIGINT= signal arrives and the execution of the
signal handler interrupts the main program just after the execution of
the =crypt()= call in the for loop, but before the check to see if the
strings match, then the main program will report a mismatch.  When we
run the program, this is what we see:

  : $ ./non_reentrant abc def
  :                         # Repeatedly type Control-C to generate SIGINT
  : Mismatch on call 109871 (mismatch=1 handled=1)
  : Mismatch on call 128061 (mismatch=2 handled=2)
  :                         # Many lines of output removed
  : Mismatch on call 727935 (mismatch=149 handled=156)
  : Mismatch on call 729547 (mismatch=150 handled=157)
  :                         # Type Control-\ to generate SIGQUIT
  : Quit (core dumped)

Comparing the mismatch and handled values in the above output, we see
that in the majority of cases where the signal handler is invoked, it
overwrites the statically allocated buffer between the call to
=crypt()= and the string comparison in =main()=.

*** Standard async-signal-safe functions

An /async-signal-safe/ function is one that the implementation
guarantees to be safe when called from a signal handler. A function is
/async-signal-safe/ *either because it is reentrant* or *because it is
not interruptible by a signal handler.*

[[Table 21.1]] lists the functions that various standards require to be
/async-signal-safe/.  In this table, the functions whose names are not
followed by a v2 or v3 were specified as /async-signal-safe/ in
POSIX.1-1990. SUSv2 added the functions marked v2 to the list, and
those marked v3 were added by SUSv3. Individual UNIX implementations
may make other functions /async-signal-safe/, but all
standards-conformant UNIX implementations must ensure that at least
these functions are /async-signal-safe/ (if they are provided by the
implementation; not all of these functions are provided on Linux).

*SUSv4* makes the following changes to [[Table 21.1]]:
 [[Table 21.1]]
- The following functions are removed: =fpathconf()=, =pathconf()=,
  and =sysconf()=.

- The following functions are added: =execl()=, =execv()=,
  =faccessat()=, =fchmodat()=, =fchownat()=, =fexecve()=, =fstatat()=,
  =futimens()=, =linkat()=, =mkdirat()=, =mkfifoat()=, =mknod()=,
  =mknodat()=, =openat()=, =readlinkat()=, =renameat()=,
  =symlinkat()=, =unlinkat()=, =utimensat()=, and =utimes()=.

**** Table 21-1
:PROPERTIES:
:CUSTOM_ID: table-21-1
:END:

Functions required to be /async-signal-safe/ by *POSIX.1-1990*,
*SUSv2*, and *SUSv3* (See [[man:signal-safety(7)]]):

#+NAME: Table 21.1
#+CAPTION: Functions required to be async-signal-safe by POSIX.1-1990, SUSv2, and SUSv3
| Function             | Notes                      |
|----------------------+----------------------------|
| abort(3)             | Added in POSIX.1-2001 TC1  |
| accept(2)            |                            |
| access(2)            |                            |
| aio_error(3)         |                            |
| aio_return(3)        |                            |
| aio_suspend(3)       | See notes below            |
| alarm(2)             |                            |
| bind(2)              |                            |
| cfgetispeed(3)       |                            |
| cfgetospeed(3)       |                            |
| cfsetispeed(3)       |                            |
| cfsetospeed(3)       |                            |
| chdir(2)             |                            |
| chmod(2)             |                            |
| chown(2)             |                            |
| clock_gettime(2)     |                            |
| close(2)             |                            |
| connect(2)           |                            |
| creat(2)             |                            |
| dup(2)               |                            |
| dup2(2)              |                            |
| execl(3)             | Added in POSIX.1-2008; see |
| notes below          |                            |
| execle(3)            | See notes below            |
| execv(3)             | Added in POSIX.1-2008      |
| execve(2)            |                            |
| _exit(2)             |                            |
| _Exit(2)             |                            |
| faccessat(2)         | Added in POSIX.1-2008      |
| fchdir(2)            | Added in POSIX.1-2008 TC1  |
| fchmod(2)            |                            |
| fchmodat(2)          | Added in POSIX.1-2008      |
| fchown(2)            |                            |
| fchownat(2)          | Added in POSIX.1-2008      |
| fcntl(2)             |                            |
| fdatasync(2)         |                            |
| fexecve(3)           | Added in POSIX.1-2008      |
| ffs(3)               | Added in POSIX.1-2008 TC2  |
| fork(2)              | See notes below            |
| fstat(2)             |                            |
| fstatat(2)           | Added in POSIX.1-2008      |
| fsync(2)             |                            |
| ftruncate(2)         |                            |
| futimens(3)          | Added in POSIX.1-2008      |
| getegid(2)           |                            |
| geteuid(2)           |                            |
| getgid(2)            |                            |
| getgroups(2)         |                            |
| getpeername(2)       |                            |
| getpgrp(2)           |                            |
| getpid(2)            |                            |
| getppid(2)           |                            |
| getsockname(2)       |                            |
| getsockopt(2)        |                            |
| getuid(2)            |                            |
| htonl(3)             | Added in POSIX.1-2008 TC2  |
| htons(3)             | Added in POSIX.1-2008 TC2  |
| kill(2)              |                            |
| link(2)              |                            |
| linkat(2)            | Added in POSIX.1-2008      |
| listen(2)            |                            |
| longjmp(3)           | Added in POSIX.1-2008 TC2; |
| see notes below      |                            |
| lseek(2)             |                            |
| lstat(2)             |                            |
| memccpy(3)           | Added in POSIX.1-2008 TC2  |
| memchr(3)            | Added in POSIX.1-2008 TC2  |
| memcmp(3)            | Added in POSIX.1-2008 TC2  |
| memcpy(3)            | Added in POSIX.1-2008 TC2  |
| memmove(3)           | Added in POSIX.1-2008 TC2  |
| memset(3)            | Added in POSIX.1-2008 TC2  |
| mkdir(2)             |                            |
| mkdirat(2)           | Added in POSIX.1-2008      |
| mkfifo(3)            |                            |
| mkfifoat(3)          | Added in POSIX.1-2008      |
| mknod(2)             | Added in POSIX.1-2008      |
| mknodat(2)           | Added in POSIX.1-2008      |
| ntohl(3)             | Added in POSIX.1-2008 TC2  |
| ntohs(3)             | Added in POSIX.1-2008 TC2  |
| open(2)              |                            |
| openat(2)            | Added in POSIX.1-2008      |
| pause(2)             |                            |
| pipe(2)              |                            |
| poll(2)              |                            |
| posix_trace_event(3) |                            |
| pselect(2)           |                            |
| pthread_kill(3)      | Added in POSIX.1-2008 TC1  |
| pthread_self(3)      | Added in POSIX.1-2008 TC1  |
| pthread_sigmask(3)   | Added in POSIX.1-2008 TC1  |
| raise(3)             |                            |
| read(2)              |                            |
| readlink(2)          |                            |
| readlinkat(2)        | Added in POSIX.1-2008      |
| recv(2)              |                            |
| recvfrom(2)          |                            |
| recvmsg(2)           |                            |
| rename(2)            |                            |
| renameat(2)          | Added in POSIX.1-2008      |
| rmdir(2)             |                            |
| select(2)            |                            |
| sem_post(3)          |                            |
| send(2)              |                            |
| sendmsg(2)           |                            |
| sendto(2)            |                            |
| setgid(2)            |                            |
| setpgid(2)           |                            |
| setsid(2)            |                            |
| setsockopt(2)        |                            |
| setuid(2)            |                            |
| shutdown(2)          |                            |
| sigaction(2)         |                            |
| sigaddset(3)         |                            |
| sigdelset(3)         |                            |
| sigemptyset(3)       |                            |
| sigfillset(3)        |                            |
| sigismember(3)       |                            |
| siglongjmp(3)        | Added in POSIX.1-2008 TC2; |
| see notes below      |                            |
| signal(2)            |                            |
| sigpause(3)          |                            |
| sigpending(2)        |                            |
| sigprocmask(2)       |                            |
| sigqueue(2)          |                            |
| sigset(3)            |                            |
| sigsuspend(2)        |                            |
| sleep(3)             |                            |
| sockatmark(3)        | Added in POSIX.1-2001 TC2  |
| socket(2)            |                            |
| socketpair(2)        |                            |
| stat(2)              |                            |
| stpcpy(3)            | Added in POSIX.1-2008 TC2  |
| stpncpy(3)           | Added in POSIX.1-2008 TC2  |
| strcat(3)            | Added in POSIX.1-2008 TC2  |
| strchr(3)            | Added in POSIX.1-2008 TC2  |
| strcmp(3)            | Added in POSIX.1-2008 TC2  |
| strcpy(3)            | Added in POSIX.1-2008 TC2  |
| strcspn(3)           | Added in POSIX.1-2008 TC2  |
| strlen(3)            | Added in POSIX.1-2008 TC2  |
| strncat(3)           | Added in POSIX.1-2008 TC2  |
| strncmp(3)           | Added in POSIX.1-2008 TC2  |
| strncpy(3)           | Added in POSIX.1-2008 TC2  |
| strnlen(3)           | Added in POSIX.1-2008 TC2  |
| strpbrk(3)           | Added in POSIX.1-2008 TC2  |
| strrchr(3)           | Added in POSIX.1-2008 TC2  |
| strspn(3)            | Added in POSIX.1-2008 TC2  |
| strstr(3)            | Added in POSIX.1-2008 TC2  |
| strtok_r(3)          | Added in POSIX.1-2008 TC2  |
| symlink(2)           |                            |
| symlinkat(2)         | Added in POSIX.1-2008      |
| tcdrain(3)           |                            |
| tcflow(3)            |                            |
| tcflush(3)           |                            |
| tcgetattr(3)         |                            |
| tcgetpgrp(3)         |                            |
| tcsendbreak(3)       |                            |
| tcsetattr(3)         |                            |
| tcsetpgrp(3)         |                            |
| time(2)              |                            |
| timer_getoverrun(2)  |                            |
| timer_gettime(2)     |                            |
| timer_settime(2)     |                            |
| times(2)             |                            |
| umask(2)             |                            |
| uname(2)             |                            |
| unlink(2)            |                            |
| unlinkat(2)          | Added in POSIX.1-2008      |
| utime(2)             |                            |
| utimensat(2)         | Added in POSIX.1-2008      |
| utimes(2)            | Added in POSIX.1-2008      |
| wait(2)              |                            |
| waitpid(2)           |                            |
| wcpcpy(3)            | Added in POSIX.1-2008 TC2  |
| wcpncpy(3)           | Added in POSIX.1-2008 TC2  |
| wcscat(3)            | Added in POSIX.1-2008 TC2  |
| wcschr(3)            | Added in POSIX.1-2008 TC2  |
| wcscmp(3)            | Added in POSIX.1-2008 TC2  |
| wcscpy(3)            | Added in POSIX.1-2008 TC2  |
| wcscspn(3)           | Added in POSIX.1-2008 TC2  |
| wcslen(3)            | Added in POSIX.1-2008 TC2  |
| wcsncat(3)           | Added in POSIX.1-2008 TC2  |
| wcsncmp(3)           | Added in POSIX.1-2008 TC2  |
| wcsncpy(3)           | Added in POSIX.1-2008 TC2  |
| wcsnlen(3)           | Added in POSIX.1-2008 TC2  |
| wcspbrk(3)           | Added in POSIX.1-2008 TC2  |
| wcsrchr(3)           | Added in POSIX.1-2008 TC2  |
| wcsspn(3)            | Added in POSIX.1-2008 TC2  |
| wcsstr(3)            | Added in POSIX.1-2008 TC2  |
| wcstok(3)            | Added in POSIX.1-2008 TC2  |
| wmemchr(3)           | Added in POSIX.1-2008 TC2  |
| wmemcmp(3)           | Added in POSIX.1-2008 TC2  |
| wmemcpy(3)           | Added in POSIX.1-2008 TC2  |
| wmemmove(3)          | Added in POSIX.1-2008 TC2  |
| wmemset(3)           | Added in POSIX.1-2008 TC2  |
| write(2)             |                            |

*** Signal Handlers Design Traps

SUSv3 notes that all functions not listed in [[Table 21.1]] are considered
to be *unsafe with respect to signals*, but points out that a function
is unsafe only when invocation of a signal handler interrupts the
execution of an unsafe function, and the handler itself also calls an
unsafe function. In other words, when writing signal handlers, we have
two choices:

- *Ensure that the code of the signal handler itself is reentrant* and
  that it calls only /async-signal-safe/ functions.

- *Block delivery of signals while executing code in the main program
  that calls unsafe functions* or *works with global data structures
  also updated by the signal handler*.

The problem with the second approach is that, in a complex program, it
can be difficult to ensure that a signal handler will never interrupt
the main program while it is calling an unsafe function. For this
reason, the above rules are often simplified to the statement that *we
must not call unsafe functions from within a signal handler.*

  #+begin_quote
  If we set up the same handler function to deal with several
  different signals or use the =SA_NODEFER= flag to =sigaction()=,
  then a handler may interrupt itself. As a consequence, the handler
  may be /nonreentrant/ if it updates global (or static) variables,
  even if they are not used by the main program.
  #+end_quote

*** Use of =errno= inside signal handlers

Because they may update =errno=, use of the functions listed in [[#table-21-1][Table
21.1]] can nevertheless render a signal handler /nonreentrant/, since
they may overwrite the =errno= value that was set by a function called
from the main program. The workaround is to save the value of =errno=
on entry to a signal handler that uses any of the functions in [[#table-21-1][Table
21.1]] and restore the =errno= value on exit from the handler, as in
the following example:

#+begin_src c
  void handler(int sig) {
    int savedErrno;
    savedErrno = errno;

    /* Now we can execute a function that might modify errno */

    errno = savedErrno;
  }
#+end_src

*** Use of unsafe functions in example programs in this book

Although =printf()= is not /async-signal-safe/, we use it in signal
handlers in various example programs in this book. We do so because
=printf()= provides an easy and concise way to demonstrate that a
signal handler has been called, and to display the contents of
relevant variables within the handler. For similar reasons, we
occasionally use a few other unsafe functions in signal handlers,
including other /stdio/ functions and =strsignal()=.

*Real-world applications should avoid calling non-async-signal-safe
functions from signal handlers.* To make this clear, each signal
handler in the example programs that uses one of these functions is
marked with a comment indicating that the usage is unsafe:

#+begin_src c
  printf("Some message\n"); /* UNSAFE */
#+end_src

** 21.1.3 Global Variables and the sig_atomic_t Data Type
:PROPERTIES:
:CUSTOM_ID: 2113-global-variables-and-the-sig_atomic_t-data-type
:END:

Notwithstanding reentrancy issues, it can be useful to share global
variables between the main program and a signal handler. This can be
safe as long as the main program correctly handles the possibility
that the signal handler may change the global variable at any
time. For example, one common design is to make a signal handler’s
sole action the setting of a global flag. This flag is periodically
checked by the main program, which then takes appropriate action in
response to the delivery of the signal (and clears the flag). *When
global variables are accessed in this way from a signal handler*, *we
should always declare them using the* =volatile= *attribute* (see
Section 6.8) *in order to prevent the compiler from performing
optimizations that result in the variable being stored in a register.*

Reading and writing global variables may involve more than one
machine-language instruction, and a signal handler may interrupt the
main program in the middle of such an instruction sequence. (We say
that access to the variable is /nonatomic/.) For this reason, the *C
language standards* and *SUSv3* specify an integer data type,
=sig_atomic_t,= for which reads and writes are guaranteed to be
atomic.  Thus, *a global flag variable that is shared between the main
program and a signal handler should be declared as follows*:

#+begin_src c
  volatile sig_atomic_t flag;
#+end_src

We show an example of the use of the =sig_atomic_t= data type in
[[file:t_sigsuspend.c][Listing 22.5]] (/t_sigsuspend.c/).

Note that the C increment (~++~) and decrement (~--~) operators *don’t
fall within the guarantee provided for* =sig_atomic_t=. On some
hardware architectures, these operations may not be atomic (refer to
Section 30.1 for more details). *All that we are guaranteed to be
safely allowed to do with a* =sig_atomic_t= *variable is set it within
the signal handler, and check it in the main program (or vice versa)*.

*C99* and *SUSv3* specify that an implementation should define two
constants (in =<stdint.h>=), =SIG_ATOMIC_MIN= and =SIG_ATOMIC_MAX=,
that define the range of values that may be assigned to variables of
type =sig_atomic_t=. The standards require that this range be at least
–127 to 127 if =sig_atomic_t= is represented as a signed value, or 0
to 255 if it is represented as an unsigned value. On Linux, these two
constants equate to the negative and positive limits for signed 32-bit
integers.

* 21.2 Other Methods of Terminating a Signal Handler
:PROPERTIES:
:CUSTOM_ID: 212-other-methods-of-terminating-a-signal-handler
:END:

All of the signal handlers that we have looked at so far complete by
returning to the main program. However, simply returning from a signal
handler sometimes isn’t desirable, or in some cases, isn’t even
useful. (We’ll see an example of where returning from a signal handler
isn’t useful when we discuss hardware-generated signals in Section
22.4.)

There are various other ways of terminating a signal handler:

1. Use =_exit()= to terminate the process. Beforehand, the handler may
   carry out some cleanup actions. Note that we can’t use =exit()= to
   terminate a signal handler, because it is not one of safe functions
   listed in [[Table 21.1]]. It is unsafe because it flushes /stdio/
   buffers prior to calling =_exit()=, as described in Section 25.1.

2. Use =kill()= or =raise()= to send a signal that kills the process
   (i.e., a signal whose default action is process termination).

3. Perform a *nonlocal goto from the signal handler*.

4. Use the =abort()= function to terminate the process with a core
   dump.

The last two of these options are described in further detail in the
following sections.

** 21.2.1 Performing a Nonlocal Goto from a Signal Handler
:PROPERTIES:
:CUSTOM_ID: 2121-performing-a-nonlocal-goto-from-a-signal-handler-429
:END:

Section 6.8 described the use of =setjmp()= and =longjmp()= to perform
a *nonlocal goto* from a function to one of its callers. We can also
use this technique from a signal handler. *This provides a way to
recover after delivery of a signal caused by a hardware exception*
(e.g., a memory access error), and *also allows us to catch a signal
and return control to a particular point in a program*. For example,
upon receipt of a =SIGINT= signal (normally generated by typing
/Control-C/), the shell performs a nonlocal goto to return control to
its main input loop (and thus read a new command).

However, there is a problem with using the standard =longjmp()=
function to exit from a signal handler. We noted earlier that, *upon
entry to the signal handler,* *the kernel automatically adds the
invoking signal*, as well as any signals specified in the
=act.sa_mask= field, to the process signal mask, *and then removes
these signals from the mask when the handler does a normal return*.

What happens to the signal mask if we exit the signal handler using
=longjmp()=?  The answer depends on the genealogy of the particular
*UNIX implementation*.  Under *System V*, =longjmp()= *doesn’t restore
the signal mask*, so that blocked signals are not unblocked upon
leaving the handler. Linux follows the System V behavior.  (This is
usually not what we want, since it leaves the signal that caused
invocation of the handler blocked.) Under *BSD-derived
implementations*, =setjmp()= *saves the signal mask in its* =env=
*argument, and the saved signal mask is restored by* =longjmp()=.
(BSD-derived implementations also provide two other functions,
=_setjmp()= and =_longjmp()=, which have the System V semantics.) *In
other words, we can’t portably use* =longjmp()= *to exit a signal
handler.*

  #+begin_quote
  If we define the =_BSD_SOURCE= feature test macro when compiling a
  program, then (the /glibc/) =setjmp()= follows the BSD semantics.
  #+end_quote

Because of this difference in the two main UNIX variants,
*POSIX.1-1990* chose not to specify the handling of the signal mask by
=setjmp()= and =longjmp()=. Instead, it defined a pair of new
functions, =sigsetjmp()= and =siglongjmp()=, that provide explicit
control of the signal mask when performing a nonlocal goto.

#+begin_src c
  #include <setjmp.h>
  int sigsetjmp(sigjmp_buf env, int savesigs);
  /* Returns 0 on initial call, nonzero on return via siglongjmp() */
  void siglongjmp(sigjmp_buf env, int val);
#+end_src

The =sigsetjmp()= and =siglongjmp()= functions operate similarly to
=setjmp()= and =longjmp()=.  The only differences are in the type of
the =env= argument (=sigjmp_buf= instead of =jmp_buf=) and the extra
=savesigs= argument to =sigsetjmp()=. If =savesigs= is nonzero, then
the process signal mask that is current at the time of the
=sigsetjmp()= call is saved in =env= and restored by a later
=siglongjmp()= call specifying the same =env= argument. If =savesigs=
is =0=, then the process signal mask is not saved and restored.

The =longjmp()= and =siglongjmp()= functions are not listed among the
/async-signal-safe/ functions in [[Table 21.1]]. This is because *calling
any /non-async-signal-safe/ function* *after performing a nonlocal
goto carries the same risks* *as calling that function from within the
signal handler*. Furthermore, if a signal handler interrupts the main
program while it is part-way through updating a data structure, and
the handler exits by performing a nonlocal goto, then the incomplete
update may leave that data structure in an inconsistent state. *One
technique that can help to avoid problems is to use* =sigprocmask()=
*to temporarily block the signal* *while sensitive updates are being
performed.*

*** Mynote: Calling Async-Signal-Unsafe After Nonlocal Goto

Calling /non-async-signal-safe/ functions is perfectly correct and the
overwhelming majority of routine-calling statements in all main
control flow. However calling them *after a* /nonlocal goto/ is
another nasty programming quagmire.

Remember that by definition /asynchronous signals/ may interrupt the
main logical flow at any point in time, and also by definition the
purpose of /nonlocal goto/ is to prevent the logical flow that called
it in the first place to resume right where it left off.

Looking at /nonlocal goto/ from that perspective, image the main flow
is right in the middle of updating some bookkeeping in the /stdio/
library when a signal is delivered. The main flow catches the signal
and lets /stdio/ in an inconsistent state expecting the restore it
when resuming. But the signal handler won't allow it to resume because
it makes a /nonlocal goto/.

Now wherever control flow lands in the main flow, (it doesn't matter
where), you are in a minefield.  Although your signal handler never
called any /non-async-signal-safe/ functions (like some /stdio/
routine) your main flow (rightly) did before the /asynchronous
interruption/ and the ensuing /nonlocal goto/, consequently, the next
time your main flow calls some /stdio/ routine you are likely to
experience some very unpleasant results.

*** Example program

- [[file:sigmask_longjmp.c][Listing 21.2]] /sigmask_longjmp.c/ (for both binaries
  /sigmask_longjmp/ and /sigmask_siglongjmp/).


[[file:sigmask_longjmp.c][Listing 21.2]] (/sigmask_longjmp.c/ for both binaries /sigmask_longjmp/
and /sigmask_siglongjmp/) demonstrates the difference in signal mask
handling for the two types of /nonlocal gotos/. This program
establishes a handler for =SIGINT=. The program is designed to allow
either =setjmp()= plus =longjmp()= or =sigsetjmp()= plus
=siglongjmp()= to be used to exit the signal handler, depending on
whether the program is compiled with the =USE_SIGSETJMP= macro
defined. The program displays the current settings of the signal mask
both on entry to the signal handler and after the /nonlocal goto/ has
transferred control from the handler back to the main program.

**** Test run after building without =USE_SIGSETJMP=

When we build /sigmask_longjmp/ program so that =longjmp()= is used to
exit the signal handler, this is what we see when we run the program:

: $ make -s sigmask_longjmp     # Default compilation causes setjmp() to be used
:
: $ ./sigmask_longjmp
: Signal mask at startup:
: <empty signal set>
: Calling setjmp()
: # Type Control-C to generate SIGINT
: Received signal 2 (Interrupt), signal mask is:
: 2 (Interrupt)
: After jump from handler, signal mask is:
: 2 (Interrupt)
: # (At this point, typing Control-C again has no effect, since SIGINT
: # is blocked) Type Control-\ to kill the program
: Quit

From the program output, we can see that, after a =longjmp()= from the
signal handler, the *signal mask remains set to the value to which it
was set on entry to the signal handler.*

  #+begin_quote
  In the above shell session, we built the program using the
  /makefile/ supplied with the source code distribution for this
  book. The =–s= option tells make not to echo the commands that it is
  executing. We use this option to avoid cluttering the session
  log. (/[Mecklenburg, 2005]/ provides a description of the GNU /make/
  program.)
  #+end_quote

**** Test run after building with =USE_SIGSETJMP=

When we compile the same source file to build /sigmask_siglongjmp/
executable that uses =siglongjmp()= to exit the handler, we see the
following:

: $ make -s sigmask_siglongjmp    # Compiles using cc –DUSE_SIGSETJMP
:
: $ ./sigmask_siglongjmp x
: Signal mask at startup:
:                 <empty signal set>
: Calling sigsetjmp()
:                                 # Type Control-C
: Received signal 2 (Interrupt), signal mask is:
:                 2 (Interrupt)
: After jump from handler, signal mask is:
:                 <empty signal set>

At this point, =SIGINT= is not blocked, because =siglongjmp()=
restored the signal mask to its original state. Next, we type
/Control-C/ again, so that the handler is once more invoked:

:                                 # Type Control-C
: Received signal 2 (Interrupt), signal mask is:
:                 2 (Interrupt)
: After jump from handler, signal mask is:
:                 <empty signal set>
:                                 # Type Control-\ to kill the program
: Quit

From the above output, we can see that =siglongjmp()= *restores the
signal mask to the value it had at the time of the* =sigsetjmp()= call
(i.e., an empty signal set).

*** Warning about nonlocal goto

****  Set nonlocal goto =env= environment before sighandler registration

[[File:sigmask_longjmp.c][Listing 21.2]] (/sigmask_longjmp.c/) also demonstrates a useful
technique for use with a signal handler that performs a /nonlocal
goto/. Because a signal can be generated at any time, it may actually
occur before the target of the /goto/ has been set up by =sigsetjmp()=
(or =setjmp()=). To prevent this possibility (which would cause the
handler to perform a /nonlocal goto/ using an uninitialized =env=
buffer), we employ a guard variable, =canJump=, to indicate whether
the =env= buffer has been initialized. If =canJump= is =false=, then
instead of doing a /nonlocal goto/, the handler simply returns. An
alternative approach is to arrange the program code so that the call
to =sigsetjmp()= (or =setjmp()=) occurs before the signal handler is
established. However, in complex programs, it may be difficult to
ensure that these two steps are performed in that order, and the use
of a guard variable may be simpler.

**** Never use =setjmp= neither =sigsetjmp= within an assignment

Note that using =#ifdef= was the simplest way of writing the program
in [[file:sigmask_longjmp.c][Listing 21.2]] (/sigmask_siglongjmp/) in a standards-conformant
fashion. In particular, we could not have replaced the =#ifdef= with
the following run-time check:

#+begin_src c
  if (useSiglongjmp)
    s = sigsetjmp(senv, 1);
  else
     s = setjmp(env);
  if (s == 0)
  /* ... */

#+end_src

This is not permitted because *SUSv3 doesn’t allow* =setjmp()= and
=sigsetjmp()= *to be used within an assignment statement* (see Section
6.8).

** 21.2.2 Terminating a Process Abnormally: abort()
:PROPERTIES:
:CUSTOM_ID: 2122-terminating-a-process-abnormally-abort()
:END:

The =abort()= function *terminates the calling process and causes it
to produce a core dump.*

#+begin_src c
  #include <stdlib.h>
  void abort(void);
#+end_src

The =abort()= function terminates the calling process by raising a
=SIGABRT= signal. *The default action for* =SIGABRT= *is to produce a
core dump file and terminate the process.* The core dump file can then
be used within a debugger to examine the state of the program at the
time of the =abort()= call.

*SUSv3* requires that =abort()= override the effect of blocking or
ignoring =SIGABRT=.  Furthermore, *SUSv3* specifies that =abort()=
*must terminate the process unless the process catches the signal with
a handler that doesn’t return*. This last statement requires a
moment’s thought. *Of the methods of terminating a signal handler
described in* [[#section-21-2][Section 21.2]], *the one that is relevant here* *is the
use of a /nonlocal goto/ to exit the handler*. *If this is done, then
the effect of* =abort()= *will be nullified;* otherwise, =abort()=
always terminates the process. In most implementations, termination is
guaranteed as follows: if the process still hasn’t terminated after
raising =SIGABRT= once (i.e., a handler catches the signal and
returns, so that execution of =abort()= is resumed), =abort()= resets
the handling of =SIGABRT= to =SIG_DFL= and raises a second =SIGABRT=,
which is guaranteed to kill the process.

If =abort()= does successfully terminate the process, then it also
flushes and closes /stdio/ streams.

An example of the use of =abort()= is provided in the error-handling
functions of [[file:../lib/error_functions.c::static void terminate(Boolean useExit3)][Listing 3.3]] (/lib/error_functions.c/).

#+NAME: Mynote 1
#+begin_quote
*The conundrum of* =abort()=:

Knowing that =abort()= kills processes by internally calling
=raise(SIGABRT)=, how does that internal flow conflicts with the main
flow in the event the process registered a signal handler for
=SIGABRT= to make some critical cleanups before terminating?

For example: After calling it from the main flow, if =abort()= resets
=SIGABRT= disposition to =SIG_DFL= immediately, it accidentally kills
your custom handler. But if it doesn't reset to =SIG_DFL= and you had
=SIG_IGN= set as =SIGABRT= disposition, the moment =abort()= control
flow calls =raise(SIGABRT)= it does absolutely nothing.
#+end_quote

See [[#exercise-21-1][Exercise 21.1]] for answer.

* 21.3 Handling a Signal on an Alternate Stack: sigaltstack()
:PROPERTIES:
:CUSTOM_ID: 213-handling-a-signal-on-an-alternate-stack-sigaltstack()
:END:

- Reference: [[man:sigaltstack(2)]]. Very good explanation of the
  concept.

Normally, *when a signal handler is invoked, the kernel creates a
frame for it on the process stack*. However, this may not be possible
if a process attempts to extend the stack beyond the maximum possible
size. For example, this may occur because the stack grows so large
that it encounters a region of mapped memory (Section 48.5) or the
upwardly growing heap, or it reaches the =RLIMIT_STACK= resource limit
(Section 36.3).

When a process attempts to grow its stack beyond the maximum possible
size, the kernel generates a =SIGSEGV= signal for the
process. However, since the stack space is exhausted, the kernel can’t
create a frame for any =SIGSEGV= handler that the program may have
established. Consequently, the handler is not invoked, and the process
is terminated (the default action for =SIGSEGV=).

If we instead need to ensure that the =SIGSEGV= signal is handled in
these circumstances, we can do the following:

1. *Allocate an area of memory*, called an /alternate signal stack/,
   to be used for the stack frame of a signal handler.

2. Use the =sigaltstack()= *system call* to inform the kernel of the
   existence of the alternate signal stack.

3. When establishing the signal handler, specify the =SA_ONSTACK=
   flag, to tell the kernel that the frame for this handler should be
   created on the alternate stack.

The =sigaltstack()= system call both establishes an alternate signal
stack and returns information about any /alternate signal stack/ that is
already established.

#+begin_src c
  #include <signal.h>
  int sigaltstack(const stack_t *sigstack, stack_t *old_sigstack);
  /* Returns 0 on success, or –1 on error */
#+end_src

The =sigstack= argument points to a structure specifying the location
and attributes of the new /alternate signal stack/. The =old_sigstack=
argument points to a structure used to return information about the
previously established /alternate signal stack/ (if there was
one). Either one of these arguments can be specified as =NULL=. For
example, we can find out about the existing /alternate signal stack/,
without changing it, by specifying =NULL= for the =sigstack=
argument. Otherwise, each of these arguments points to a structure of
the following type:

#+begin_src c
  typedef struct {
    void *ss_sp;    /* Starting address of alternate stack */
    int ss_flags;   /* Flags: SS_ONSTACK, SS_DISABLE */
    size_t ss_size; /* Size of alternate stack */
  } stack_t;
#+end_src

The =ss_sp= and =ss_size= fields specify the size and location of the
alternate signal stack.  *When actually using the /alternate signal
stack/,* *the kernel automatically takes care of aligning the value
given in* =ss_sp= *to an address boundary that is suitable for the
hardware architecture.*

*Typically, the /alternate signal stack/ is either* *statically
allocated or dynamically allocated on the heap*. *SUSv3* specifies the
constant =SIGSTKSZ= to be used as a typical value when sizing the
/alternate stack/, and =MINSIGSTKSZ= as the minimum size required to
invoke a signal handler. On *Linux/x86-32*, these constants are
defined with the values 8192 and 2048, respectively.

*The kernel doesn’t resize an alternate signal stack.* *If the stack
overflows the space we have allocated for it, then chaos results*
(e.g., overwriting of variables beyond the limits of the stack). This
is not usually a problem — *because we normally use an /alternate
signal stack/* *to handle the special case of the standard stack
overflowing*, typically only one or a few frames are allocated on the
stack. The job of the =SIGSEGV= handler is either to perform some
cleanup and terminate the process or to unwind the standard stack
using a nonlocal goto.

The =ss_flags= field contains one of the following values:

- =SS_ONSTACK= ::  If this flag is set when retrieving information
  about the currently established alternate signal stack
  (=old_sigstack=), it indicates that the process is currently
  executing on the alternate signal stack. Attempts to establish a new
  alternate signal stack while the process is already running on an
  alternate signal stack result in an error (=EPERM=) from
  =sigaltstack()=.

- =SS_DISABLE= ::  Returned in =old_sigstack=, this flag indicates
  that there is no currently established alternate signal stack. When
  specified in =sigstack=, this disables a currently established
  alternate signal stack.

[[file:t_sigaltstack.c][Listing 21.3]] (/t_sigaltstack.c/) demonstrates the establishment and
use of an /alternate signal stack/. Depending on whether it is
compiled with =NO_SIGALTSTACK= or not the source code respectively
yields /t_sigstack/ or /t_sigaltstack/ binaries. It enables you to
have a first hand comparative experience of how /alternate signal
stack/ saves the day when you set =SIGSEGV= dispositions.

After establishing an alternate signal stack and a handler for
=SIGSEGV=, this program calls a function that infinitely recurses, so
that the stack overflows and the process is sent a =SIGSEGV=
signal. When we run the program, this is what we see:

  : $ ulimit -s unlimited      # ←─ Not necessary
  :
  : $ ./t_sigaltstack
  : Top of standard stack is near 0x7fffa0e42a5c
  : Alternate stack is at         0x6356e38bb6b0-0x6356e38dbfff
  : Call    1 - top of stack near 0x7fffa0e22a20
  : Call    2 - top of stack near 0x7fffa0e029f0
  :
  :                            # Many intervening lines of output removed
  :
  : Call   62 - top of stack near 0x7fffa0681eb0
  : Call   63 - top of stack near 0x7fffa0661e80
  : Caught signal 11 (Segmentation fault)
  : Top of handler stack near 0x6356e38bd164

In this shell session, the =ulimit= command is used to remove any
=RLIMIT_STACK= resource limit that may have been set in the shell. We
explain this resource limit in Section 36.3.

* 21.4 The SA_SIGINFO Flag
:PROPERTIES:
:CUSTOM_ID: 214-the-sa_siginfo-flag
:END:

Setting the =SA_SIGINFO= flag when establishing a handler with
=sigaction()= allows the handler to obtain additional information
about a signal when it is delivered. In order to obtain this
information, we must declare the handler as follows:

#+begin_src c
  void handler(int sig, siginfo_t *siginfo, void *ucontext);
#+end_src

The first argument, =sig=, is the signal number, as for a standard
signal handler. The second argument, =siginfo=, is a structure used to
provide the additional information about the signal. We describe this
structure below. The last argument, =ucontext=, is also described
below.

Since the above signal handler has a different prototype from a
standard signal handler, C typing rules mean that we can’t use the
=sa_handler= field of the =sigaction= structure to specify the address
of the handler. Instead, we must use an alternative field:
=sa_sigaction=. *In other words, the definition of the sigaction
structure is somewhat more complex than was shown in* [[file:CHAPTER_20.org::#section-20-13][Section
20.13]]. In full, the structure is defined as follows:

#+begin_src c
  struct sigaction {
    union {
      void (*sa_handler)(int);
      void (*sa_sigaction)(int, siginfo_t *, void *);
    } __sigaction_handler;
    sigset_t sa_mask;
    int sa_flags;
    void (*sa_restorer)(void);
  };
  /* Following defines make the union fields look like simple fields
  in the parent structure */
  #define sa_handler __sigaction_handler.sa_handler
  #define sa_sigaction __sigaction_handler.sa_sigaction
#+end_src

#+NAME: Mynote 2
#+begin_quote
Perhaps it happened to you that your *Integrated Development
Environment* or *Editor* gave you /auto-completion/ on all =struct
sigaction= fields but never on =sa_handler= field: you enter =sa.= or
=sa->= (where =sa= is a declared =struct sigaction= or pointer to it),
then trigger your *IDE* /auto-completion/ but nothing happens. *The
reason is* =struct sigaction= *doesn't have any field named*
=sa_handler= *which is a macro created to shorten the edition of the
real* =__sigaction_handler= =union= field and its alternate
sub-fields, either =sa_handler= or =sa_sigaction=.
#+end_quote

The =sigaction= structure uses a =union= to combine the =sa_sigaction=
and =sa_handler= fields. (Most other UNIX implementations similarly
use a union for this purpose.)  Using a =union= is possible because
only one of these fields is required during a particular call to
=sigaction()=. (*However, this can lead to strange bugs if we naively
expect to be able to set the* =sa_handler= *and* =sa_sigaction=
*fields independently of one another*, *perhaps because we reuse a
single* =sigaction= *structure in multiple* =sigaction()= *calls to
establish handlers for different signals.*)

Here is an example of the use of =SA_SIGINFO= to establish a signal
handler:

#+begin_src c
  struct sigaction act;
  sigemptyset(&act.sa_mask);
  act.sa_sigaction = handler;
  act.sa_flags = SA_SIGINFO;
  if (sigaction(SIGINT, &act, NULL) == -1)
    errExit("sigaction");
#+end_src

For complete examples of the use of the =SA_SIGINFO= flag, see Listing
22-3 (page 462) and Listing 23-5 (page 500).

** The =siginfo_t= structure
:PROPERTIES:
:CUSTOM_ID: section-21-4-the-siginfo_t-structure
:END:

- Reference: [[man:sigaction(2)]];

The =siginfo_t= structure passed as the second argument to a signal
handler that is established with =SA_SIGINFO= has the following form:

#+begin_src c
  typedef struct {
    int si_signo; /* Signal number */
    int si_code; /* Signal code */
    int si_trapno; /* Trap number for hardware-generated signal
                      (unused on most architectures) */
    union sigval si_value; /* Accompanying data from sigqueue() */
    pid_t si_pid; /* Process ID of sending process */
    uid_t si_uid; /* Real user ID of sender */
    int si_errno; /* Error number (generally unused) */
    void *si_addr; /* Address that generated signal
                      (hardware-generated signals only) */
    int si_overrun; /* Overrun count (Linux 2.6, POSIX timers) */
    int si_timerid; /* (Kernel-internal) Timer ID
                       (Linux 2.6, POSIX timers) */
    long si_band; /* Band event (SIGPOLL/SIGIO) */
    int si_fd; /* File descriptor (SIGPOLL/SIGIO) */
    int si_status; /* Exit status or signal (SIGCHLD) */
    clock_t si_utime; /* User CPU time (SIGCHLD) */
    clock_t si_stime; /* System CPU time (SIGCHLD) */
  } siginfo_t;

#+end_src

The =_POSIX_C_SOURCE= feature test macro must be defined with a value
greater than or equal to *199309* in order to make the declaration of
the =siginfo_t= structure visible from =<signal.h>=.

On Linux, as on most UNIX implementations, *many of the fields in the*
=siginfo_t= *structure are combined into a* =union=, *since not all of
the fields are needed for each signal.* (See =<bits/siginfo.h>= for
details.)

Upon entry to a signal handler, the fields of the =siginfo_t=
structure are set as follows:

- =si_signo= ::  This field is set for all signals. It contains the
  number of the signal causing invocation of the handler — that is,
  the same value as the =sig= argument to the handler.

- =si_code= ::  This field is set for all signals. It contains a code
  providing further information about the origin of the signal, as
  shown in [[Table 21.2]].

- =si_value= ::  This field contains the accompanying data for a
  signal sent via =sigqueue()=. We describe =sigqueue()= in Section
  22.8.1.

- =si_pid= ::  For signals sent via =kill()= or =sigqueue()=, this
  field is set to the process ID of the sending process.

- =si_uid= ::  For signals sent via =kill()= or =sigqueue()=, this
  field is set to the real user ID of the sending process. The system
  provides the real user ID of the sending process because that is
  more informative than providing the effective user ID. Consider the
  permission rules for sending signals described in [[file:CHAPTER_20.org::#section-20-5-sending-permission][Section 20.5]]: if
  the effective user ID grants the sender permission to send the
  signal, then that user ID must either be 0 (i.e., a privileged
  process), or be the same as the real user ID or saved set-user-ID of
  the receiving process. In this case, it could be useful for the
  receiver to know the sender’s real user ID, which may be different
  from the effective user ID (e.g., if the sender is a set-user-ID
  program).

- =si_errno= ::  If this field is set to a nonzero value, then it
  contains an error number (like =errno=) that identifies the cause of
  the signal. This field is generally unused on Linux.

- =si_addr= ::  This field is set only for hardware-generated
  =SIGBUS=, =SIGSEGV=, =SIGILL=, and =SIGFPE= signals. For the
  =SIGBUS= and =SIGSEGV= signals, this field contains the address that
  caused the invalid memory reference. For the =SIGILL= and =SIGFPE=
  signals, this field contains the address of the program instruction
  that caused the signal.

*The following fields, which are nonstandard Linux extensions,* *are
set only on the delivery of a signal generated* *on expiration of a
POSIX timer (see Section 23.6)*:

- =si_timerid= ::  This field contains an ID that the kernel uses
  internally to identify the timer.

- =si_overrun= ::  This field is set to the overrun count for the
  timer.

*The following two fields are set only for the delivery of a* =SIGIO=
*signal (Section 63.3)*:

- =si_band= ::  This field contains the “band event” value associated
  with the I/O event. (In versions of /glibc/ up until 2.3.2,
  =si_band= was typed as =int=.)

- =si_fd= ::  This field contains the number of the file descriptor
  associated with the I/O event. This field is not specified in
  *SUSv3*, but it is present on many other implementations.

*The following fields are set only for the delivery of a* =SIGCHLD=
*signal (Section 26.3)*:

- =si_status= ::  This field contains either the exit status of the
  child (if =si_code= is =CLD_EXITED=) or the number of the signal
  sent to the child (i.e., the number of the signal that terminated or
  stopped the child, as described in Section 26.1.3).

- =si_utime= ::  This field contains the user CPU time used by the
  child process. In kernels before 2.6, and since 2.6.27, this is
  measured in system clock ticks (divide by
  =sysconf(_SC_CLK_TCK)=). In 2.6 kernels before 2.6.27, a bug meant
  that this field reported times measured in (user-configurable)
  /jiffies/ (see Section 10.6). This field is not specified in
  *SUSv3*, but it is present on many other implementations.

- =si_stime= ::  This field contains the system CPU time used by the
  child process. See the description of the =si_utime= field. This
  field is not specified in *SUSv3*, but it is present on many other
  implementations.

The =si_code= field provides further information about the origin of
the signal, using the values shown in [[#table-21-2][Table 21.2]]. Not all of the
signal-specific values shown in the second column of this table occur
on all UNIX implementations and hardware architectures (especially in
the case of the four hardware-generated signals =SIGBUS=, =SIGSEGV=,
=SIGILL=, and =SIGFPE=), although all of these constants are defined
on Linux and most appear in *SUSv3*.

Note the following additional points about the values shown in [[#table-21-2][Table
21.2]]:

- The values =SI_KERNEL= and =SI_SIGIO= are Linux-specific. They are
  not specified in *SUSv3* and do not appear on other UNIX
  implementations.

- =SI_SIGIO= is employed only in *Linux 2.2*. From kernel 2.4 onward,
  Linux instead employs the =POLL_*= constants shown in the table.

    #+begin_quote
    *SUSv4* specifies the =psiginfo()= function, whose purpose is
    similar to =psignal()= ([[file:CHAPTER_20.org::#section-20-8][Section 20.8]]). The =psiginfo()= function
    takes two arguments: *a pointer to a* =siginfo_t= *structure* and
    *a message string*. It prints the message string on standard
    error, followed by information about the signal described in the
    =siginfo_t= structure. The =psiginfo()= function is provided by
    /glibc/ since version 2.10. The /glibc/ implementation prints the
    signal description, the origin of the signal (as indicated by the
    =si_code= field), and, for some signals, other fields from the
    =siginfo_t= structure. The =psiginfo()= function is new in
    *SUSv4*, and it is not available on all systems.
    #+end_quote

*** Table 21-2: Values returned in the =siginfo_t.si_code= field
:PROPERTIES:
:CUSTOM_ID: table-21-2
:END:

For a regular signal, the following list shows the values which can be
placed in =si_code= for any signal, along with the reason that the
signal was generated.

#+NAME: Table 21.2
#+CAPTION: Values returned in the si_code field of the siginfo_t structure
| Signal        | ~si_code~ value                          | Origin of signal                                                            |
|               | <20>                                     | <40>                                                                         |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| Any           | SI_USER                                  | kill(2)                                                                     |
|               | SI_KERNEL                                | Sent by the kernel                                                          |
|               | SI_QUEUE                                 | sigqueue(3)                                                                 |
|               | SI_TIMER                                 | POSIX timer expired                                                         |
|               | SI_MESGQ (since Linux 2.6.6)             | POSIX message queue state changed; see mq_notify(3)                         |
|               | SI_ASYNCIO                               | AIO completed                                                               |
|               | SI_SIGIO                                 | Queued  SIGIO (only up to Linux 2.2; from Linux 2.4 onward                  |
|               |                                          | SIGIO/SIGPOLL fills in si_code as described below)                          |
|               | SI_TKILL (since Linux 2.4.19)            | tkill(2) or tgkill(2)                                                       |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGBUS        | BUS_ADRALN                               | Invalid address alignment                                                   |
|               | BUS_ADRERR                               | Nonexistent physical address                                                |
|               | BUS_OBJERR                               | Object-specific hardware error                                              |
|               | BUS_MCEERR_AR (since Linux 2.6.32)       | Hardware  memory  error  consumed on a machine check; actio required        |
|               | BUS_MCEERR_AO (since Linux 2.6.32)       | Hardware memory error detected in process but not  consumed action optional |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGCHLD       | CLD_EXITED                               | Child has exited                                                            |
|               | CLD_KILLED                               | Child was killed                                                            |
|               | CLD_DUMPED                               | Child terminated abnormally                                                 |
|               | CLD_TRAPPED                              | Traced child has trapped                                                    |
|               | CLD_STOPPED                              | Child has stopped                                                           |
|               | CLD_CONTINUED (since Linux 2.6.9)        | Stopped child has continued                                                 |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGFPE        | FPE_INTDIV                               | Integer divide by zero                                                      |
|               | FPE_INTOVF                               | Integer overflow                                                            |
|               | FPE_FLTDIV                               | Floating-point divide by zero                                               |
|               | FPE_FLTOVF                               | Floating-point overflow                                                     |
|               | FPE_FLTUND                               | Floating-point underflow                                                    |
|               | FPE_FLTRES                               | Floating-point inexact result                                               |
|               | FPE_FLTINV                               | Floating-point invalid operation                                            |
|               | FPE_FLTSUB                               | Subscript out of range                                                      |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGILL        | ILL_ILLOPC                               | Illegal opcode                                                              |
|               | ILL_ILLOPN                               | Illegal operand                                                             |
|               | ILL_ILLADR                               | Illegal addressing mode                                                     |
|               | ILL_ILLTRP                               | Illegal trap                                                                |
|               | ILL_PRVOPC                               | Privileged opcode                                                           |
|               | ILL_PRVREG                               | Privileged register                                                         |
|               | ILL_COPROC                               | Coprocessor error                                                           |
|               | ILL_BADSTK                               | Internal stack error                                                        |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGIO/SIGPOLL | POLL_IN                                  | Data input available                                                        |
|               | POLL_OUT                                 | Output buffers available                                                    |
|               | POLL_MSG                                 | Input message available                                                     |
|               | POLL_ERR                                 | I/O error                                                                   |
|               | POLL_PRI                                 | High priority input available                                               |
|               | POLL_HUP                                 | Device disconnected                                                         |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGSEGV       | SEGV_MAPERR                              | Address not mapped to object                                                |
|               | SEGV_ACCERR                              | Invalid permissions for mapped object                                       |
|               | SEGV_BNDERR (since Linux 3.19)           | Failed address bound checks                                                 |
|               | SEGV_PKUERR (since Linux 4.6)            | Access was denied by memory protection keys.  See  pkeys(7).                |
|               |                                          | The protection key which applied to this access is available via si_pkey    |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGTRAP       | TRAP_BRKPT                               | Process breakpoint                                                          |
|               | TRAP_TRACE                               | Process trace trap                                                          |
|               | TRAP_BRANCH (since Linux 2.4, IA64 only) | Process taken branch trap                                                   |
|               | TRAP_HWBKPT (since Linux 2.4, IA64 only) | Hardware breakpoint/watchpoint                                              |
|---------------+------------------------------------------+-----------------------------------------------------------------------------|
| SIGSYS        | SYS_SECCOMP (since Linux 3.5)            | Triggered by a seccomp(2) filter rule                                       |
|               |                                          |                                                                             |

** The =ucontext= argument

The final argument passed to a handler established with the
=SA_SIGINFO= flag, =ucontext=, is a pointer to a structure of type
=ucontext_t= (defined in =<ucontext.h>=).  (*SUSv3* uses a void
pointer for this argument because it doesn’t specify any of the
details of the argument.) This structure provides so-called
user-context information describing the process state prior to
invocation of the signal handler, including the previous process
signal mask and saved register values (e.g., program counter and stack
pointer). This information is rarely used in signal handlers, so we
don’t go into further details.

  #+begin_quote
  Another use of =ucontext_t= structures is with the functions
  =getcontext()=, =makecontext()=, =setcontext()=, and
  =swapcontext()=, which allow a process to retrieve, create, change,
  and swap execution contexts, respectively. (These operations are
  somewhat like =setjmp()= and =longjmp()=, but more general.) These
  functions can be used to implement coroutines, where the thread of
  execution of a process alternates between two (or more)
  functions. *SUSv3* specifies these functions, *but marks them
  obsolete*. *SUSv4 removes the specifications*, *and suggests that
  applications should be rewritten to use POSIX threads instead*.  The
  /glibc/ manual provides further information about these functions.
  #+end_quote

* 21.5 Interruption and Restarting of System Calls
:PROPERTIES:
:CUSTOM_ID: 215-interruption-and-restarting-of-system-calls
:END:

** Handle System Calls Interruption by Signals

Consider the following scenario:

1. We establish a handler for some signal.
2. We make a blocking system call, for example, a =read()= from a
   terminal device, which blocks until input is supplied.
3. While the system call is blocked, the signal for which we
   established a handler is delivered, and its signal handler is
   invoked.

What happens after the signal handler returns? By default, the system
call fails with the error =EINTR= (“Interrupted function”). This can
be a useful feature. In Section 23.3, we’ll see how to use a timer
(which results in the delivery of a =SIGALRM= signal) to set a timeout
on a blocking system call such as =read()=.

Often, however, we would prefer to continue the execution of an
interrupted system call. To do this, we could use code such as the
following to manually restart a system call in the event that it is
interrupted by a signal handler:

#+begin_src c
  while ((cnt = read(fd, buf, BUF_SIZE)) == -1 && errno == EINTR)
    continue; /* Do nothing loop body */

  if (cnt == -1) /* read() failed with other than EINTR */
    systmErr("read");
#+end_src

If we frequently write code such as the above, it can be useful to
define a /macro/ such as the following:

#+begin_src c
  #define NO_EINTR(stmt) while ((stmt) == -1 && errno == EINTR);
#+end_src

Using this /macro/, we can rewrite the earlier =read()= call as
follows:

#+begin_src c
  NO_EINTR(cnt = read(fd, buf, BUF_SIZE));

  if (cnt == -1) /* read() failed with other than EINTR */
    systmErr("read");
#+end_src

  #+begin_quote
  The *GNU C library* provides a (nonstandard) /macro/ with the same
  purpose as our =NO_EINTR()= /macro/ in =<unistd.h>=. The macro is
  called =TEMP_FAILURE_RETRY()= and is made available if the
  =_GNU_SOURCE= feature test macro is defined.
  #+end_quote

Even if we employ a /macro/ like =NO_EINTR()=, having signal handlers
interrupt system calls can be inconvenient, since we must add code to
each blocking system call (assuming that we want to restart the call
in each case). Instead, we can specify the =SA_RESTART= flag when
establishing the signal handler with =sigaction()=, so that *system
calls are automatically restarted by the kernel* *on the process’s
behalf*. This means that we don’t need to handle a possible =EINTR=
error return for these system calls.

The =SA_RESTART= flag is a per-signal setting. In other words, we can
allow handlers for some signals to interrupt blocking system calls,
while others permit automatic restarting of system calls.

** Effects Of =SA_RESTART= On System Calls And Library Functions

Unfortunately, *not all blocking system calls automatically restart as
a result of specifying* =SA_RESTART=. The reasons for this are partly
historical:

- Restarting of system calls was introduced in 4.2BSD, and covered
  interrupted calls to =wait()= and =waitpid()=, as well as the
  following I/O system calls: =read()=, =readv()=, =write()=,
  =writev()=, and blocking =ioctl()= operations. *The I/O system calls
  are interruptible, and hence automatically restarted by*
  =SA_RESTART= *only when operating on a “slow” device*. Slow devices
  include *terminals*, *pipes*, *FIFOs*, and *sockets*. On these file
  types, various I/O operations may block. (By contrast, *disk files
  don’t fall into the category of slow devices*, because disk I/O
  operations generally can be immediately satisfied via the /buffer
  cache/. If a disk I/O is required, the kernel puts the process to
  sleep until the I/O completes.)

- A number of other blocking system calls are derived from System V,
  which did not initially provide for restarting of system calls.

*** System calls automatically restarted by =SA_RESTART=

On Linux, the following blocking system calls (and library functions
layered on top of system calls) are automatically restarted if
interrupted by a signal handler established using the =SA_RESTART=
flag:

- *The system calls used to wait for a child process* (Section 26.1):
  =wait()=, =waitpid()=, =wait3()=, =wait4()=, =and waitid()=.

- *The I/O system calls* =read()=, =readv()=, =write()=, =writev()=,
  *and* =ioctl()= *when applied to “slow” devices*. In cases where
  data has already been partially transferred at the time of signal
  delivery, the input and output system calls will be interrupted, but
  return a success status: an integer indicating how many bytes were
  successfully transferred.

- The =open()= system call, *in cases where it can block* (e.g., when
  opening *FIFOs*, as described in Section 44.7).

- *Various system calls used with sockets*: =accept()=, =accept4()=,
  =connect()=, =send()=, =sendmsg()=, =sendto()=, =recv()=,
  =recvfrom()=, and =recvmsg()=. (On Linux, these system calls are not
  automatically restarted if a timeout has been set on the socket
  using =setsockopt()=. See the [[man:signal(7)]] manual page for
  details.)

- *The system calls used for I/O on POSIX message queues*:
  =mq_receive()=, =mq_timedreceive()=, =mq_send()=, and
  =mq_timedsend()=.

- *The system calls and library functions used to place file locks*:
  =flock()=, =fcntl()=, and =lockf()=.

- The =FUTEX_WAIT= operation of the Linux-specific =futex()= system
  call.

- *The* =sem_wait()= *and* =sem_timedwait()= *functions used to
  decrement a POSIX semaphore*. (On some UNIX implementations,
  =sem_wait()= is restarted if the =SA_RESTART= flag is specified.)

- *The functions used to synchronize POSIX threads*:
  =pthread_mutex_lock()=, =pthread_mutex_trylock()=,
  =pthread_mutex_timedlock()=, =pthread_cond_wait()=, and
  =pthread_cond_timedwait()=.

In kernels before 2.6.22, =futex()=, =sem_wait()=, and
=sem_timedwait()= always failed with the error =EINTR= when
interrupted, regardless of the setting of the =SA_RESTART= flag.

*** System calls never restarted

The following blocking system calls (and library functions layered on
top of system calls) *are never automatically restarted* (*even if*
=SA_RESTART= *is specified*):

- The =poll()=, =ppoll()=, =select()=, and =pselect()= I/O
  multiplexing calls. (*SUSv3* explicitly states that the behavior of
  =select()= and =pselect()= when interrupted by a signal handler is
  unspecified, regardless of the setting of =SA_RESTART=.)

- The Linux-specific =epoll_wait()= and =epoll_pwait()= system calls.

- The Linux-specific =io_getevents()= system call.

- *The blocking system calls used with System V message queues and
  semaphores*: =semop()=, =semtimedop()=, =msgrcv()=, and
  =msgsnd()=. (Although System V did not originally provide automatic
  restarting of system calls, on some UNIX implementations, these
  system calls are restarted if the =SA_RESTART= flag is specified.)

- A =read()= from an =inotify= file descriptor.

- *The system calls and library functions designed to suspend
  execution of a program for a specified period*: =sleep()=,
  =nanosleep()=, and =clock_nanosleep()=.

- *The system calls designed specifically to wait until a signal is
  delivered*: =pause()=, =sigsuspend()=, =sigtimedwait()=, and
  =sigwaitinfo()=.

** Modifying the =SA_RESTART= flag for a signal

The =siginterrupt()= function changes the =SA_RESTART= setting
associated with a signal.

#+begin_src c
  #include <signal.h>
  int siginterrupt(int sig, int flag);
  /* Returns 0 on success, or –1 on error */
#+end_src

If =flag= is true (=1=), then a handler for the signal =sig= *will
interrupt blocking system calls*. If flag is false (=0=), then
blocking system calls *will be restarted after execution of a handler
for* =sig=.

The =siginterrupt()= function works by using =sigaction()= to fetch a
copy of the signal’s current disposition, tweaking the =SA_RESTART=
flag in the returned =oldact= structure, and then calling
=sigaction()= once more to update the signal’s disposition.

*SUSv4 marks* =siginterrupt()= *obsolete, recommending the use of*
=sigaction()= *instead for this purpose.*

** Unhandled stop signals can generate =EINTR= for some Linux system calls

*On Linux, certain blocking system calls can return* =EINTR= *even in
the absence of a signal handler*. This can occur if the system call is
blocked and the process is stopped by a signal (=SIGSTOP=, =SIGTSTP=,
=SIGTTIN=, or =SIGTTOU=), and then resumed by delivery of a =SIGCONT=
signal.

The following system calls and functions exhibit this behavior:
=epoll_pwait()=, =epoll_wait()=, =read()= from an =inotify= file
descriptor, =semop()=, =semtimedop()=, =sigtimedwait()=, and
=sigwaitinfo()=.

In kernels before 2.6.24, =poll()= also exhibited this behavior, as
did =sem_wait()=, =sem_timedwait()=, =futex(FUTEX_WAIT)=, in kernels
before 2.6.22, =msgrcv()= and =msgsnd()= in kernels before 2.6.9, and
=nanosleep()= in Linux 2.4 and earlier.

In Linux 2.4 and earlier, =sleep()= can also be interrupted in this
manner, but, instead of returning an error, it returns the number of
remaining unslept seconds.

The upshot of this behavior is that if there is a chance that our
program may be stopped and restarted by signals, then we may need to
include code to restart these system calls, even in a program that
doesn’t install handlers for the stop signals.

* 21.6 Summary
:PROPERTIES:
:CUSTOM_ID: 216-summary
:END:

In this chapter, we considered a range of factors that affect the
operation and design of *signal handlers*.

Because signals are not queued, a signal handler must sometimes be
coded to deal with the possibility that multiple events of a
particular type have occurred, even though only one signal was
delivered. The issue of reentrancy affects how we can update global
variables and limits the set of functions that we can safely call from
a signal handler.

Instead of returning, a signal handler can terminate in a variety of
other ways, including calling =_exit()=, terminating the process by
sending a signal (=kill()=, =raise()=, or =abort()=), or performing a
/nonlocal goto/. Using =sigsetjmp()= and =siglongjmp()= provides a
program with explicit control of the treatment of the process signal
mask when a /nonlocal goto/ is performed.

We can use =sigaltstack()= to define an alternate signal stack for a
process. This is an area of memory that is used instead of the
standard process stack when invoking a signal handler. An alternate
signal stack is useful in cases where the standard stack has been
exhausted by growing too large (at which point the kernel sends a
=SIGSEGV= signal to the process).

The =sigaction()= =SA_SIGINFO= flag allows us to establish a signal
handler that receives additional information about a signal. This
information is supplied via a =siginfo_t= structure whose address is
passed as an argument to the signal handler.

When a signal handler interrupts a blocked system call, the system
call fails with the error =EINTR=. We can take advantage of this
behavior to, for example, set a timer on a blocking system
call. Interrupted system calls can be manually restarted if
desired. Alternatively, establishing the signal handler with the
=sigaction()= =SA_RESTART= flag causes many (but not all) system calls
to be automatically restarted.

** Further information

See the sources listed in [[file:CHAPTER_20.org::#2015-summary][Section 20.15]].

* 21.7 Exercises
:PROPERTIES:
:CUSTOM_ID: 217-exercises
:END:

** Exercise 21.1
:PROPERTIES:
:CUSTOM_ID: exercise-21-1
:END:

Implement =abort()=.

*** Answer
- [[file:yabort.c][yabort]], [[file:exr2101_test.c][exr2101_test]].
