/* =========================================================================
 * Created on: <Thu May 14 09:45:29 +01 2026>
 * Time-stamp: <Sun May 17 19:06:56 +01 2026 by owner>
 * Author    : Copyright (C) Michael Kerrisk, 2026.
 *             See the file COPYING.gpl-v3 for details.
 * Desc      : ~/coding/c_prog/tlpi/signals/ouch.c -
 *
 * Listing 20.1: Catch the SIGINT signal, generated by typing
 * control-C (^C). Note that although we use signal() to establish the
 * signal handler in this program, the use of sigaction() is always
 * preferable for this task.
 * ========================================================================= */
#include "../lib/tlpi_hdr.h"
#include <signal.h>

static void sigHandler(int sig) {
  printf("Ouch!\n"); /* UNSAFE: (see Section 21.1.2) */
}

int main(int argc, char *argv[]) {
  int j;

  /* Establish handler for SIGINT. Here we use the simpler signal()
     API to establish a signal handler, but for the reasons described in
     Section 22.7 of TLPI, sigaction() is the (strongly) preferred API
     for this task. */

  if (signal(SIGINT, sigHandler) == SIG_ERR)
    systmErr("signal");

  /* Loop continuously waiting for signals to be delivered */

  for (j = 0;; j++) {
    printf("%d\n", j);
    sleep(3); /* Loop slowly... */
  }
}
