/* =========================================================================
 * Created on: <Thu May 14 09:52:23 +01 2026>
 * Time-stamp: <Sun May 17 19:06:56 +01 2026 by owner>
 * Author    : owner
 * Desc      : ~/coding/c_prog/tlpi/signals/youch.c -
 *
 * Pratice [[file:ouch.c][Listing 20.1]]: Catch the SIGINT signal,
 * generated by typing control-C (^C). Note that although we use
 * signal() to establish the signal handler in this program, the use
 * of sigaction() is always preferable for this task.
 * ========================================================================= */
#define _GNU_SOURCE

#include "../lib/tlpi_hdr.h"
#include <signal.h>

/* sighandler_t routine; */

static void sigHandler(int sig) {
  printf("Éékyé!\n"); /* UNSAFE: not async-signal-safe */
}

int main(int argc, char *argv[argc + 1]) {
  int j;

  if (signal(SIGINT, sigHandler) == SIG_ERR)
    systmErr("signal() failed");

  for (j = 0;; j++) {
    printf("%d\n", j);
    sleep(3); /* Loop slowly */
  }

  return EXIT_SUCCESS;
}
